services:
  docker:
    container_name: jenkins-docker
    image: docker:dind
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
    privileged: true
  blueocean:
    build: .
    restart: on-failure
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home


volumes:
  jenkins-docker-certs:
  jenkins-data:

#docker run --name jenkins-docker --rm --detach
  #--privileged --network jenkins --network-alias docker
  #--env DOCKER_TLS_CERTDIR=/certs
  #--volume jenkins-docker-certs:/certs/client 
  #--volume jenkins-data:/var/jenkins_home 
  #--publish 2376:2376 
  #docker:dind