name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code
    - name: Dotnet Build
      run: dotnet build
    - name: Dotnet Test
      run: dotnet test
    - name: npm build
      run: cd DotnetTemplate.Web && npm run build
    - name: npm lint
      run: cd DotnetTemplate.Web && npm run lint
    - name: npm test
      run: cd DotnetTemplate.Web && npm run test
